### ISSUE TITLE
(Carbon) button icons are supposed to have 75% opacity and render incorrectly if the opacity is 100%

### ISSUE THREAD

**Issue by TorutheRedFox** [xan1242/NFS-XtendedInput#18] opened 2022-05-02 12:09 UTC
this might be the case for MW too but I'm not 100% sure

**Comment by AeroWidescreen** [comment] 2022-05-02 18:22
I'm not sure what you mean by this. Could you clarify?  Here's a comparison between Xbox 360 (Xenia) and PC.

![Compare](https://i.imgur.com/G405AJc.gif)

Icons aside, they look exactly the same.

**Comment by xan1242** [comment] 2022-05-03 14:49
Not sure about this one either... I'll check against a real PS2 and PS3 but if you're comparing against PCSX2 it is probably an alpha blend bug.

**Comment by TorutheRedFox** [comment] 2022-05-03 15:15
I'm comparing against texture dumps, they're 75% opacity, and when I made it 100% when making my icons, they came out way too bright (so much that it started to wash out the colors)

**Comment by xan1242** [comment] 2022-05-03 15:50
And how are you dumping the textures exactly?

Here's the same spot on a real PS2 (captured with a camera):

![IMG_2393_scale](https://user-images.githubusercontent.com/8014093/166488468-8575bd5d-ec33-4a34-bbed-4bf7f6599233.png)


Whatever you're doing is not a bug related to this project...

**Comment by xan1242** [comment] 2022-05-03 16:50
![image](https://user-images.githubusercontent.com/8014093/166500545-9caf7f8e-1e51-4cc1-8ccf-bdd1ffa4f01c.png)

Circle image opened in GIMP.

This is the texture ripped from the PS3 version, but is the same one used in the PS2 version anyway.

No opacity is really visible here on any pixel other than the ones used for smoothing the image.

Whatever you did clipped the color values and caused them to be washed out in the resulting image. Maybe it is a TPK setting but that does not concern this project directly.

Closing.

**Closed by xan1242** 2022-05-03 16:50 UTC
